export type KpiCategory =
  | 'productiviteit'
  | 'efficientie'
  | 'personeel'
  | 'flow'
  | 'voorraad'
  | 'kwaliteit'
  | 'veiligheid'
  | 'klantbetrouwbaarheid'

export type KpiReadiness = 'operational' | 'partial' | 'needs_data'

export interface GroeiplanKpiDefinition {
  id: string
  category: KpiCategory
  name: string
  description: string
  unit: string
  /** Statische beoordeling vóór data-analyse */
  readiness: KpiReadiness
  dataSource: string
  gaps: string[]
  relatedAdmin?: string
  /** Groeiplan-referentie (shop-floor / strategisch) */
  groeiplanRef?: string
}

export const GROEIPLAN_REPORT_START = '2026-01'

export const KPI_CATEGORY_LABELS: Record<KpiCategory, string> = {
  productiviteit: 'Productiviteit',
  efficientie: 'Efficiëntie',
  personeel: 'Personeelsinzet',
  flow: 'Flow & doorlooptijd',
  voorraad: 'Voorraad',
  kwaliteit: 'Kwaliteit',
  veiligheid: 'Veiligheid',
  klantbetrouwbaarheid: 'Klantbetrouwbaarheid',
}

export const GROEIPLAN_KPIS: GroeiplanKpiDefinition[] = [
  {
    id: 'prepack_items',
    category: 'productiviteit',
    name: 'Prepack — items verpakt',
    description: 'Totaal aantal verpakte eenheden via de Prepack-flow per maand.',
    unit: 'stuks',
    readiness: 'operational',
    dataSource: 'packed_items.date_packed',
    gaps: [],
    relatedAdmin: '/admin/prepack',
    groeiplanRef: 'Output per werkplek / periode',
  },
  {
    id: 'airtec_items',
    category: 'productiviteit',
    name: 'Airtec — items verpakt',
    description: 'Totaal aantal verpakte Airtec-eenheden per maand.',
    unit: 'stuks',
    readiness: 'operational',
    dataSource: 'packed_items_airtec.date_packed',
    gaps: [],
    relatedAdmin: '/admin/airtec',
    groeiplanRef: 'Output per werkplek / periode',
  },
  {
    id: 'grote_inpak_consumption',
    category: 'productiviteit',
    name: 'Grote inpak — verbruik kisten',
    description: 'Maandelijks verbruik van kisttypes (consumptie/registraties).',
    unit: 'stuks',
    readiness: 'operational',
    dataSource: 'grote_inpak_packed_consumption.scan_date',
    gaps: ['Geen splitsing Wilrijk vs Willebroek in consumptietabel'],
    relatedAdmin: '/grote-inpak',
    groeiplanRef: 'Output per vestiging',
  },
  {
    id: 'production_pieces',
    category: 'productiviteit',
    name: 'Productieorders — afgemelde stuks',
    description: 'Som van afgemelde productie-aantallen via tijdregistratie op orders.',
    unit: 'stuks',
    readiness: 'partial',
    dataSource: 'time_logs.production_quantity (type production_order)',
    gaps: ['Niet alle orders registreren quantity consequent', 'Geen BC-realtime koppeling'],
    relatedAdmin: '/admin/production-order-kpi',
    groeiplanRef: 'Output per order / werkplek',
  },
  {
    id: 'prepack_items_per_hour',
    category: 'efficientie',
    name: 'Prepack — items per manuur',
    description: 'Verhouding verpakte items tot geregistreerde manuren Prepack.',
    unit: 'stuks/u',
    readiness: 'operational',
    dataSource: 'packed_items + time_logs (items_to_pack)',
    gaps: ['Overlap-correctie op manuren niet in maandaggregaat'],
    relatedAdmin: '/admin/prepack',
    groeiplanRef: 'Efficiëntie verpakking',
  },
  {
    id: 'airtec_items_per_hour',
    category: 'efficientie',
    name: 'Airtec — items per manuur',
    description: 'Verhouding verpakte items tot geregistreerde manuren Airtec.',
    unit: 'stuks/u',
    readiness: 'operational',
    dataSource: 'packed_items_airtec + time_logs (items_to_pack_airtec)',
    gaps: ['Overlap-correctie op manuren niet in maandaggregaat'],
    relatedAdmin: '/admin/airtec',
    groeiplanRef: 'Efficiëntie verpakking',
  },
  {
    id: 'production_hours_per_piece',
    category: 'efficientie',
    name: 'Productie — uren per stuk',
    description: 'Gemiddelde geregistreerde uren per afgemeld stuk op productieorders.',
    unit: 'u/stuk',
    readiness: 'partial',
    dataSource: 'time_logs (production_order)',
    gaps: ['Quantity niet altijd ingevuld', 'Geen normtijden ter vergelijking'],
    relatedAdmin: '/admin/production-order-kpi',
    groeiplanRef: 'Uren per order',
  },
  {
    id: 'prepack_manhours',
    category: 'personeel',
    name: 'Prepack — manuren',
    description: 'Totaal geregistreerde manuren op Prepack per maand.',
    unit: 'u',
    readiness: 'operational',
    dataSource: 'time_logs (items_to_pack)',
    gaps: ['Geen koppeling met Protime/planningsuren'],
    relatedAdmin: '/admin/prepack',
    groeiplanRef: 'Uren per order / medewerker',
  },
  {
    id: 'airtec_manhours',
    category: 'personeel',
    name: 'Airtec — manuren',
    description: 'Totaal geregistreerde manuren op Airtec per maand.',
    unit: 'u',
    readiness: 'operational',
    dataSource: 'time_logs (items_to_pack_airtec)',
    gaps: ['Geen koppeling met Protime/planningsuren'],
    relatedAdmin: '/admin/airtec',
    groeiplanRef: 'Uren per order / medewerker',
  },
  {
    id: 'employee_attendance',
    category: 'personeel',
    name: 'Aanwezigheidsgraad',
    description: 'Percentage medewerkers met status “aanwezig” t.o.v. ingevulde dagstatussen.',
    unit: '%',
    readiness: 'partial',
    dataSource: 'employee_daily_status',
    gaps: ['Dagplanning niet dagelijks voor alle medewerkers ingevuld', 'Geen Wilrijk/Willebroek-split'],
    relatedAdmin: '/admin/competentie-matrix',
    groeiplanRef: 'Capaciteitsbenutting',
  },
  {
    id: 'prepack_incoming',
    category: 'flow',
    name: 'Prepack — instroom goederen',
    description: 'Aantal binnengekomen eenheden (wachtrij + verpakt op ontvangstdatum).',
    unit: 'stuks',
    readiness: 'operational',
    dataSource: 'items_to_pack.date_added + packed_items.date_added',
    gaps: [],
    relatedAdmin: '/admin/prepack-airtec',
    groeiplanRef: 'Planning vs realisatie (instroom)',
  },
  {
    id: 'prepack_inflow_vs_packed',
    category: 'flow',
    name: 'Prepack — instroom/verpakt ratio',
    description: 'Verhouding instroom tot verpakte output; >1 wijst op groeiende backlog.',
    unit: 'ratio',
    readiness: 'operational',
    dataSource: 'prepack instroom + packed_items',
    gaps: [],
    relatedAdmin: '/admin/prepack-airtec',
    groeiplanRef: 'Flow-balans',
  },
  {
    id: 'grote_inpak_overdue',
    category: 'flow',
    name: 'Grote inpak — gem. overdue cases',
    description: 'Gemiddeld aantal overdue cases per dag (snapshot KPI-historiek).',
    unit: 'cases',
    readiness: 'operational',
    dataSource: 'grote_inpak_kpi_history.overdue_cases',
    gaps: ['Historiek start vanaf eerste PILS-run met snapshot', 'Locaties geaggregeerd'],
    relatedAdmin: '/grote-inpak',
    groeiplanRef: 'Doorlooptijd / achterstand',
  },
  {
    id: 'grote_inpak_leadtime',
    category: 'flow',
    name: 'Grote inpak — gem. doorlooptijd',
    description: 'Gemiddelde doorlooptijd (dagen) van gearchiveerde cases per maand.',
    unit: 'dagen',
    readiness: 'partial',
    dataSource: 'grote_inpak_case_archive.doorlooptijd_dagen',
    gaps: ['Archief dekt enkel cases die van PILS verdwijnen'],
    relatedAdmin: '/grote-inpak',
    groeiplanRef: 'Doorlooptijd per bewerking',
  },
  {
    id: 'wood_consumption',
    category: 'voorraad',
    name: 'Hout — verbruik',
    description: 'Totaal houtverbruik (consumptie) per maand.',
    unit: 'planken',
    readiness: 'operational',
    dataSource: 'wood_consumption',
    gaps: ['Geen automatische BC-voorraadafstemming'],
    relatedAdmin: '/wood/picking',
    groeiplanRef: 'Voorraadrotatie',
  },
  {
    id: 'wood_stock_corrections',
    category: 'voorraad',
    name: 'Hout — stockcorrecties',
    description: 'Aantal voorraadtelling-correcties per maand (indicator datakwaliteit).',
    unit: 'correcties',
    readiness: 'partial',
    dataSource: 'wood_stock_corrections',
    gaps: ['Correctie ≠ absolute voorraadnauwkeurigheid'],
    relatedAdmin: '/wood/stock-count',
    groeiplanRef: 'Voorraadbetrouwbaarheid',
  },
  {
    id: 'weert_stock_to_order',
    category: 'voorraad',
    name: 'Weert — lijnen te bestellen',
    description: 'Momentopname: aantal voorraadlijnen onder minimum (geen maandhistoriek).',
    unit: 'lijnen',
    readiness: 'needs_data',
    dataSource: 'weert_stock_items (snapshot)',
    gaps: ['Geen historische snapshots — maandtrend niet beschikbaar', 'Alleen Weert-locatie'],
    relatedAdmin: '/admin/weert-stock',
    groeiplanRef: 'Min/max voorraad',
  },
  {
    id: 'quality_reject_rate',
    category: 'kwaliteit',
    name: 'Productinspectie — afkeurpercentage',
    description: 'Percentage afgekeurde productcontroles t.o.v. totaal aantal controles.',
    unit: '%',
    readiness: 'operational',
    dataSource: 'product_controles.status',
    gaps: ['Dekking afhankelijk van gebruik inspectie-app'],
    relatedAdmin: '/admin/monitor-controles',
    groeiplanRef: 'Kwaliteitsopvolging',
  },
  {
    id: 'airtec_scan_match',
    category: 'kwaliteit',
    name: 'Airtec — scan match-ratio',
    description: 'Percentage succesvolle dubbele scans (match) bij Airtec verpakken.',
    unit: '%',
    readiness: 'partial',
    dataSource: 'airtec_scan_log.result',
    gaps: ['Alleen Airtec scan-flow', 'Mismatch ≠ productkwaliteit'],
    relatedAdmin: '/admin/airtec-scan-log',
    groeiplanRef: 'Proceskwaliteit labels',
  },
  {
    id: 'safety_incidents',
    category: 'veiligheid',
    name: 'Veiligheidsincidenten',
    description: 'Geregistreerde Arbo-/veiligheidsincidenten per maand.',
    unit: 'incidenten',
    readiness: 'needs_data',
    dataSource: '—',
    gaps: ['Geen veiligheidsmodule in Prodwilrijk', 'Manuele registratie extern nodig'],
    groeiplanRef: 'Veiligheid & welzijn',
  },
  {
    id: 'safety_near_miss',
    category: 'veiligheid',
    name: 'Bijna-ongevallen / LMRA',
    description: 'Registratie van bijna-ongevallen of LMRA-uitvoering.',
    unit: 'meldingen',
    readiness: 'needs_data',
    dataSource: '—',
    gaps: ['Geen dataverzameling voorzien'],
    groeiplanRef: 'Preventiecultuur',
  },
  {
    id: 'forecast_shift_rate',
    category: 'klantbetrouwbaarheid',
    name: 'Grote inpak — forecast-wijzigingen',
    description: 'Aantal forecast-wijzigingen per maand (indicator planstabiliteit).',
    unit: 'wijzigingen',
    readiness: 'partial',
    dataSource: 'grote_inpak_forecast_changes',
    gaps: ['Geen directe klant-OTIF-meting'],
    relatedAdmin: '/grote-inpak',
    groeiplanRef: 'Planning vs realisatie',
  },
  {
    id: 'customer_requests_open',
    category: 'klantbetrouwbaarheid',
    name: 'Grote inpak — open klantvragen',
    description: 'Aantal open klantvragen (snapshot, geen maandhistoriek).',
    unit: 'vragen',
    readiness: 'needs_data',
    dataSource: 'grote_inpak_customer_requests (snapshot)',
    gaps: ['Geen historische maand-snapshots', 'Geen OTIF/levertermijn KPI'],
    relatedAdmin: '/grote-inpak',
    groeiplanRef: 'Klantbetrouwbaarheid',
  },
  {
    id: 'planning_vs_realisation',
    category: 'klantbetrouwbaarheid',
    name: 'Planning vs realisatie',
    description: 'Vergelijking geplande productie/output met gerealiseerde output per vestiging.',
    unit: '%',
    readiness: 'needs_data',
    dataSource: 'BC planning + shop-floor (gepland)',
    gaps: [
      'Geen geautomatiseerde BC-planning import',
      'Shop-floor planning niet gekoppeld aan output-KPI',
      'Multi-site vergelijking niet operationeel',
    ],
    relatedAdmin: '/shop-floor/planning',
    groeiplanRef: 'Planning versus realisatie (kern-KPI groeiplan)',
  },
]

export function getKpiDefinition(id: string): GroeiplanKpiDefinition | undefined {
  return GROEIPLAN_KPIS.find((k) => k.id === id)
}
